### ISSUE TITLE
Template validation fails with InvalidContentLink message "Unable to download deployment content from 'https://cdn.f5.com..."

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-azure-arm-templates-v2#2]
## Describe the bug
When you deploy ARM template within Azure Portal and hit the Purchase button, ARM validation fails with following :

Generic error message :

{"telemetryId":"6ab9598e-572c-4b23-b257-8abc49e82589","bladeInstanceId":"Blade_09bf802f384a46be9064fbe79d747785_7_0","galleryItemId":"MyGalleryItem","createBlade":"DeployToAzure","code":"MultipleErrorsOccurred","message":"Multiple error occurred: BadRequest,BadRequest,BadRequest. Please see details.","details":[{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/v1.0.0.0/examples/modules/access/access.json'. The tracking Id is '66e23f80-71d9-441c-8ab0-aa80d11ae5da'. Please see https://aka.ms/arm-deploy for usage details."},{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/v1.0.0.0/examples/modules/network/network.json'. The tracking Id is '66e23f80-71d9-441c-8ab0-aa80d11ae5da'. Please see https://aka.ms/arm-deploy for usage details."},{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/v1.0.0.0/examples/modules/dag/dag.json'. The tracking Id is '66e23f80-71d9-441c-8ab0-aa80d11ae5da'. Please see https://aka.ms/arm-deploy for usage details."}]}

RAW error message is :

{
  "telemetryId": "6ab9598e-572c-4b23-b257-8abc49e82589",
  "bladeInstanceId": "Blade_09bf802f384a46be9064fbe79d747785_7_0",
  "galleryItemId": "MyGalleryItem",
  "createBlade": "DeployToAzure",
  "code": "MultipleErrorsOccurred",
  "message": "Multiple error occurred: BadRequest,BadRequest,BadRequest. Please see details.",
  "details": [
    {
      "code": "InvalidContentLink",
      "message": "Unable to download deployment content from 'https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/v1.0.0.0/examples/modules/access/access.json'. The tracking Id is '66e23f80-71d9-441c-8ab0-aa80d11ae5da'. Please see https://aka.ms/arm-deploy for usage details."
    },
    {
      "code": "InvalidContentLink",
      "message": "Unable to download deployment content from 'https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/v1.0.0.0/examples/modules/network/network.json'. The tracking Id is '66e23f80-71d9-441c-8ab0-aa80d11ae5da'. Please see https://aka.ms/arm-deploy for usage details."
    },
    {
      "code": "InvalidContentLink",
      "message": "Unable to download deployment content from 'https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/v1.0.0.0/examples/modules/dag/dag.json'. The tracking Id is '66e23f80-71d9-441c-8ab0-aa80d11ae5da'. Please see https://aka.ms/arm-deploy for usage details."
    }
  ]
}

## Expected behavior
 
ARM template should deploy resources
 
## Current behavior
 
Failure to deploy
 
## Possible solution
 
FIX the CDN availability or amend "Template Base Url" parameter with another URL link

 
## Steps to reproduce
 
Deploy V2 PAYG template

**Comment by mikeshimkus** [comment]
Hi, I uploaded the template modules to the location referenced in the example template; it should work now.  I created internal issue 2259 to track the fix.

**Comment by trace1918** [comment]
This is still a problem. Clonig the repo results in this error:
```
Azure Error: MultipleErrorsOccurred
Message: Multiple error occurred: BadRequest,BadRequest,BadRequest. Please see details.
Exception Details:
	Error Code: InvalidContentLink
	Message: Unable to download deployment content from 'https://github.com/F5Networks/f5-azure-arm-templates-v2/examples/modules/access/access.json'. The tracking Id is '30a37a51-5d77-48e1-bcee-89b28379e5d1'. Please see https://aka.ms/arm-deploy for usage details.
	Error Code: InvalidContentLink
	Message: Unable to download deployment content from 'https://github.com/F5Networks/f5-azure-arm-templates-v2/examples/modules/network/network.json'. The tracking Id is '30a37a51-5d77-48e1-bcee-89b28379e5d1'. Please see https://aka.ms/arm-deploy for usage details.
	Error Code: InvalidContentLink
	Message: Unable to download deployment content from 'https://github.com/F5Networks/f5-azure-arm-templates-v2/examples/modules/dag/dag.json'. The tracking Id is '30a37a51-5d77-48e1-bcee-89b28379e5d1'. Please see https://aka.ms/arm-deploy for usage details.
```

If I try to edit the URLs to point to the GitHub URL instead I get past it but that results in this error:

```
Azure Error: MultipleErrorsOccurred
Message: Multiple error occurred: BadRequest,BadRequest,BadRequest. Please see details.
Exception Details:
	Error Code: InvalidTemplate
	Message: Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'.
	Error Code: InvalidTemplate
	Message: Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'.
	Error Code: InvalidTemplate
	Message: Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'.
```

Also when I try to simply click the "Deploy to Azure" button it results in this error:

`There was an error downloading the template from URI 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v1.0.0.0/examples/autoscale/payg/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. `

**Comment by mikeshimkus** [comment]
Hi, for the button issue, please copy the link and modify it to https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates-v2/v1.0.0.0/examples/autoscale/payg/azuredeploy.json, then paste in a browser.

For the cloning issue, it appears the templateBaseUrl and artifactLocation parameters may not be correct.  Are you following the customization steps here: https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/master/examples#cloud-configuration

**Comment by andreasjacobi** [comment]
Hi,
Thanks, that worked for the button issue. There is also a typo in the BigIQ button, it is not only missing the -v2 but bigiq is misspelled:

`- **PAYG**: This allows you to use pay-as-you-go hourly billing.

  [![Deploy to Azure](http://azuredeploy.net/deploybutton.png)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates-v2%2Fv1.0.0.0%2Fexamples%2Fautoscale%2Fbiqiq%2Fazuredeploy.json)
  [![Deploy to Azure](http://azuredeploy.net/deploybutton.png)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates-v2%2Fv1.0.0.0%2Fexamples%2Fautoscale%2Fbigiq%2Fazuredeploy.json)`

I will look more into the parameters. For me this issue is solved.
Thanks

**Comment by shyawnkarim** [comment]
Closing.

These issues were resolved with [Release 1.1](https://github.com/F5Networks/f5-azure-arm-templates-v2/releases/tag/v1.1.0.0).
